"""Mappings of keywords to their likely DLL names."""

from typing import Optional

DLL_MAP = {
    # Native API functions (ntdll.dll)
    "nt": "ntdll.dll",
    "zw": "ntdll.dll",
    "rtl": "ntdll.dll",
    "allocatevirtualmemory": "ntdll.dll",
    "freevirtualmemory": "ntdll.dll",
    # KERNEL32.DLL - PROCESS & THREAD MANAGEMENT (EXPANDED)
    "createprocess": "kernel32.dll",  # CreateProcess, CreateProcessAsUser, etc.
    "createprocessa": "kernel32.dll",
    "createprocessw": "kernel32.dll",
    "openprocess": "kernel32.dll",
    "terminateprocess": "kernel32.dll",
    "getprocessid": "kernel32.dll",
    "getcurrentprocess": "kernel32.dll",
    "getcurrentprocessid": "kernel32.dll",
    "getprocessversion": "kernel32.dll",
    "getprocesstimes": "kernel32.dll",
    "getprocessiofounters": "kernel32.dll",
    "getprocessworkingsetsize": "kernel32.dll",
    "setprocessworkingsetsize": "kernel32.dll",
    "getprocessaffinitymask": "kernel32.dll",
    "setprocessaffinitymask": "kernel32.dll",
    "getprocesspriorityboost": "kernel32.dll",
    "setprocesspriorityboost": "kernel32.dll",
    "getprocesspriorityclass": "kernel32.dll",
    "setprocesspriorityclass": "kernel32.dll",
    "exitprocess": "kernel32.dll",
    "getexitcodeprocess": "kernel32.dll",
    "getthreadid": "kernel32.dll",
    "createthread": "kernel32.dll",
    "createremotethread": "kernel32.dll",
    "createremotethreadex": "kernel32.dll",
    "openthread": "kernel32.dll",
    "suspendthread": "kernel32.dll",
    "resumethread": "kernel32.dll",
    "terminatethread": "kernel32.dll",
    "getcurrentthread": "kernel32.dll",
    "getcurrentthreadid": "kernel32.dll",
    "getthreadtimes": "kernel32.dll",
    "getthreadpriority": "kernel32.dll",
    "setthreadpriority": "kernel32.dll",
    "getthreadpriorityboost": "kernel32.dll",
    "setthreadpriorityboost": "kernel32.dll",
    "getthreadaffinitymask": "kernel32.dll",
    "setthreadaffinitymask": "kernel32.dll",
    "getthreadcontext": "kernel32.dll",
    "setthreadcontext": "kernel32.dll",
    "exitthread": "kernel32.dll",
    "getexitcodethread": "kernel32.dll",
    "waitforsingleobject": "kernel32.dll",
    "waitforsingleobjectex": "kernel32.dll",
    "waitformultipleobjects": "kernel32.dll",
    "waitformultipleobjectsex": "kernel32.dll",
    "signalObjectandwait": "kernel32.dll",
    "tlsalloc": "kernel32.dll",
    "tlsfree": "kernel32.dll",
    "tlsgetvalue": "kernel32.dll",
    "tlssetvalue": "kernel32.dll",
    # KERNEL32.DLL - MEMORY MANAGEMENT (EXPANDED)
    "virtualalloc": "kernel32.dll",
    "virtualallocex": "kernel32.dll",
    "virtualallocexnuma": "kernel32.dll",
    "virtualalloc2": "kernel32.dll",
    "virtualfree": "kernel32.dll",
    "virtualfreeex": "kernel32.dll",
    "virtualprotect": "kernel32.dll",
    "virtualprotectex": "kernel32.dll",
    "virtualquery": "kernel32.dll",
    "virtualqueryex": "kernel32.dll",
    "virtuallock": "kernel32.dll",
    "virtualunlock": "kernel32.dll",
    "readprocessmemory": "kernel32.dll",
    "writeprocessmemory": "kernel32.dll",
    "createfilemapping": "kernel32.dll",
    "createfilemappinga": "kernel32.dll",
    "createfilemappingw": "kernel32.dll",
    "createfilemappingnuma": "kernel32.dll",
    "mapviewoffile": "kernel32.dll",
    "mapviewoffileex": "kernel32.dll",
    "mapviewoffilenuma": "kernel32.dll",
    "unmapviewoffile": "kernel32.dll",
    "flushviewoffile": "kernel32.dll",
    "heapcreate": "kernel32.dll",
    "heapalloc": "kernel32.dll",
    "heapfree": "kernel32.dll",
    "heapdestroy": "kernel32.dll",
    "heaplock": "kernel32.dll",
    "heapunlock": "kernel32.dll",
    "heapvalidate": "kernel32.dll",
    "heapsize": "kernel32.dll",
    "heapwalk": "kernel32.dll",
    "getprocessheap": "kernel32.dll",
    "getprocessheaps": "kernel32.dll",
    "heapsetinformation": "kernel32.dll",
    "heapqueryinformation": "kernel32.dll",
    "globalalloc": "kernel32.dll",
    "globalrealloc": "kernel32.dll",
    "globalfree": "kernel32.dll",
    "globallock": "kernel32.dll",
    "globalunlock": "kernel32.dll",
    "globalsize": "kernel32.dll",
    "globalflags": "kernel32.dll",
    "globalhandle": "kernel32.dll",
    "localalloc": "kernel32.dll",
    "localrealloc": "kernel32.dll",
    "localfree": "kernel32.dll",
    "locallock": "kernel32.dll",
    "localunlock": "kernel32.dll",
    "localsize": "kernel32.dll",
    "localflags": "kernel32.dll",
    "localhandle": "kernel32.dll",
    # KERNEL32.DLL - FILE OPERATIONS (EXPANDED)
    "createfile": "kernel32.dll",
    "createfilea": "kernel32.dll",
    "createfilew": "kernel32.dll",
    "createfile2": "kernel32.dll",
    "readfile": "kernel32.dll",
    "writefile": "kernel32.dll",
    "readfileex": "kernel32.dll",
    "writefileex": "kernel32.dll",
    "deletefile": "kernel32.dll",
    "deletefilea": "kernel32.dll",
    "deletefilew": "kernel32.dll",
    "copyfile": "kernel32.dll",
    "copyfilea": "kernel32.dll",
    "copyfilew": "kernel32.dll",
    "copyfileex": "kernel32.dll",
    "copyfileexa": "kernel32.dll",
    "copyfileexw": "kernel32.dll",
    "movefile": "kernel32.dll",
    "movefilea": "kernel32.dll",
    "movefilew": "kernel32.dll",
    "movefileex": "kernel32.dll",
    "movefileexa": "kernel32.dll",
    "movefileexw": "kernel32.dll",
    "findfirstfile": "kernel32.dll",
    "findfirstfilea": "kernel32.dll",
    "findfirstfilew": "kernel32.dll",
    "findfirstfileex": "kernel32.dll",
    "findfirstfileexa": "kernel32.dll",
    "findfirstfileexw": "kernel32.dll",
    "findnextfile": "kernel32.dll",
    "findnextfilea": "kernel32.dll",
    "findnextfilew": "kernel32.dll",
    "findclose": "kernel32.dll",
    "getfileattributes": "kernel32.dll",
    "getfileattributesa": "kernel32.dll",
    "getfileattributesw": "kernel32.dll",
    "getfileattributesex": "kernel32.dll",
    "getfileattributesexa": "kernel32.dll",
    "getfileattributesexw": "kernel32.dll",
    "setfileattributes": "kernel32.dll",
    "setfileattributesa": "kernel32.dll",
    "setfileattributesw": "kernel32.dll",
    "getfiletime": "kernel32.dll",
    "setfiletime": "kernel32.dll",
    "getfilesize": "kernel32.dll",
    "getfilesizeex": "kernel32.dll",
    "setfilepointer": "kernel32.dll",
    "setfilepointerex": "kernel32.dll",
    "getfullpathname": "kernel32.dll",
    "getfullpathnamea": "kernel32.dll",
    "getfullpathnamew": "kernel32.dll",
    "getcurrentdirectory": "kernel32.dll",
    "getcurrentdirectorya": "kernel32.dll",
    "getcurrentdirectoryw": "kernel32.dll",
    "setcurrentdirectory": "kernel32.dll",
    "setcurrentdirectorya": "kernel32.dll",
    "setcurrentdirectoryw": "kernel32.dll",
    "createdirectory": "kernel32.dll",
    "createdirectorya": "kernel32.dll",
    "createdirectoryw": "kernel32.dll",
    "removedirectory": "kernel32.dll",
    "removedirectorya": "kernel32.dll",
    "removedirectoryw": "kernel32.dll",
    "getlogicaldrives": "kernel32.dll",
    "getlogicaldrivesrings": "kernel32.dll",
    "getdrivetypea": "kernel32.dll",
    "getdrivetypew": "kernel32.dll",
    "getdiskfreespace": "kernel32.dll",
    "getdiskfreespacea": "kernel32.dll",
    "getdiskfreespacew": "kernel32.dll",
    "getdiskfreespaceex": "kernel32.dll",
    "getdiskfreespaceexa": "kernel32.dll",
    "getdiskfreespaceexw": "kernel32.dll",
    # KERNEL32.DLL - LIBRARY LOADING
    "loadlibrary": "kernel32.dll",
    "freelibrary": "kernel32.dll",
    "getprocaddress": "kernel32.dll",
    "getmodulehandle": "kernel32.dll",
    "getmodulefilename": "kernel32.dll",
    # KERNEL32.DLL - OTHER
    "timezone": "kernel32.dll",
    "dynamic": "kernel32.dll",
    "time": "kernel32.dll",
    "getlasterror": "kernel32.dll",
    "setlasterror": "kernel32.dll",
    "formatmessage": "kernel32.dll",
    "sleep": "kernel32.dll",
    "getcommandline": "kernel32.dll",
    "getcomputername": "kernel32.dll",
    "getenvironmentvariable": "kernel32.dll",
    "setenvironmentvariable": "kernel32.dll",
    # ADVAPI32.DLL - SECURITY & TOKENS
    "adjusttokenprivileges": "advapi32.dll",
    "duplicatetoken": "advapi32.dll",
    "openprocesstoken": "advapi32.dll",
    "openthreadtoken": "advapi32.dll",
    "lookupprivilegevalue": "advapi32.dll",
    "impersonateloggedonuser": "advapi32.dll",
    "reverttoself": "advapi32.dll",
    "logonuser": "advapi32.dll",
    "createprocessasuser": "advapi32.dll",  # IMPORTANT!
    "createprocesswithlogon": "advapi32.dll",
    "createprocesswithtoken": "advapi32.dll",
    # ADVAPI32.DLL - REGISTRY
    "regopen": "advapi32.dll",
    "regcreate": "advapi32.dll",
    "regquery": "advapi32.dll",
    "regset": "advapi32.dll",
    "regdelete": "advapi32.dll",
    "regenum": "advapi32.dll",
    "regclose": "advapi32.dll",
    # ADVAPI32.DLL - SERVICES
    "openscmanager": "advapi32.dll",
    "openservice": "advapi32.dll",
    "createservice": "advapi32.dll",
    "deleteservice": "advapi32.dll",
    "startservice": "advapi32.dll",
    "controlservice": "advapi32.dll",
    "queryservicestatus": "advapi32.dll",
    "enumservices": "advapi32.dll",
    # ADVAPI32.DLL - CRYPTOGRAPHY
    "cryptacquire": "advapi32.dll",
    "cryptrelease": "advapi32.dll",
    "cryptcreate": "advapi32.dll",
    "cryptdecrypt": "advapi32.dll",
    "cryptencrypt": "advapi32.dll",
    "cryptgenkey": "advapi32.dll",
    "crypthash": "advapi32.dll",
    # ADVAPI32.DLL - ACL & SECURITY
    "geteffectiverights": "advapi32.dll",
    "seteffectiverights": "advapi32.dll",
    "getacl": "advapi32.dll",
    "setacl": "advapi32.dll",
    "getsecurityinfo": "advapi32.dll",
    "setsecurityinfo": "advapi32.dll",
    # USER32.DLL - WINDOW MANAGEMENT
    "findwindow": "user32.dll",
    "findwindowex": "user32.dll",
    "getwindowtext": "user32.dll",
    "setwindowtext": "user32.dll",
    "showwindow": "user32.dll",
    "createwindow": "user32.dll",
    "destroywindow": "user32.dll",
    "getwindowrect": "user32.dll",
    "setwindowpos": "user32.dll",
    "enumwindows": "user32.dll",
    "enumchildwindows": "user32.dll",
    # USER32.DLL - MESSAGING
    "sendmessage": "user32.dll",
    "postmessage": "user32.dll",
    "getmessage": "user32.dll",
    "peekmessage": "user32.dll",
    "dispatchmessage": "user32.dll",
    "messagebox": "user32.dll",
    # USER32.DLL - HOOKING
    "setwindowshook": "user32.dll",
    "unhookwindowshook": "user32.dll",
    "callnexthook": "user32.dll",
    # USER32.DLL - INPUT
    "getkeyboardstate": "user32.dll",
    "setkeyboardstate": "user32.dll",
    "getcursorpos": "user32.dll",
    "setcursorpos": "user32.dll",
    "mouse_event": "user32.dll",
    "keybd_event": "user32.dll",
    # USER32.DLL - OTHER
    "getdc": "user32.dll",
    "releasedc": "user32.dll",
    "getdesktopwindow": "user32.dll",
    "getforegroundwindow": "user32.dll",
    "setforegroundwindow": "user32.dll",
    # GDI32.DLL - Graphics/GDI
    "textout": "gdi32.dll",
    "bitblt": "gdi32.dll",
    "stretchblt": "gdi32.dll",
    "drawtext": "gdi32.dll",
    "getstockobject": "gdi32.dll",
    "deletedc": "gdi32.dll",
    "createdc": "gdi32.dll",
    "createcompatibledc": "gdi32.dll",
    "createbrush": "gdi32.dll",
    "createpen": "gdi32.dll",
    "createfont": "gdi32.dll",
    "selectobject": "gdi32.dll",
    "deleteobject": "gdi32.dll",
    # PSAPI.DLL - Process Information
    "enumprocesses": "psapi.dll",
    "enumprocessmodules": "psapi.dll",
    "getprocessimagefilename": "psapi.dll",
    "getprocessmemoryinfo": "psapi.dll",
    "getperformanceinfo": "psapi.dll",
    # WS2_32.DLL - Networking
    "wsastartup": "ws2_32.dll",
    "wsacleanup": "ws2_32.dll",
    "socket": "ws2_32.dll",
    "bind": "ws2_32.dll",
    "listen": "ws2_32.dll",
    "accept": "ws2_32.dll",
    "connect": "ws2_32.dll",
    "send": "ws2_32.dll",
    "recv": "ws2_32.dll",
    "closesocket": "ws2_32.dll",
    "gethostbyname": "ws2_32.dll",
    "inet_addr": "ws2_32.dll",
    # WININET.DLL - Internet (EXPANDED)
    "internetopen": "wininet.dll",
    "internetopena": "wininet.dll",
    "internetopenw": "wininet.dll",
    "internetconnect": "wininet.dll",
    "internetconnecta": "wininet.dll",
    "internetconnectw": "wininet.dll",
    "httpopenrequest": "wininet.dll",
    "httpopenrequesta": "wininet.dll",
    "httpopenrequestw": "wininet.dll",
    "httpsendrequest": "wininet.dll",
    "httpsendrequesta": "wininet.dll",
    "httpsendrequest": "wininet.dll",
    "httpqueryinfo": "wininet.dll",
    "httpqueryinfoa": "wininet.dll",
    "httpqueryinfow": "wininet.dll",
    "internetreadfile": "wininet.dll",
    "internetwritefile": "wininet.dll",
    "internetclosehandle": "wininet.dll",
    "internetfindnextfile": "wininet.dll",
    "internetopenurlw": "wininet.dll",
    "internetopenurla": "wininet.dll",
    "internetsetstatuscallback": "wininet.dll",
    "internetsetoption": "wininet.dll",
    "internetsetoptiona": "wininet.dll",
    "internetsetoptionw": "wininet.dll",
    "internetqueryoption": "wininet.dll",
    "internetquerydataavailable": "wininet.dll",
    "urldownloadtofile": "urlmon.dll",
    "urldownloadtofilew": "urlmon.dll",
    "urldownloadtofilea": "urlmon.dll",
    "urldownloadtocache": "urlmon.dll",
    # WINHTTP.DLL - WinHTTP
    "winhttpopen": "winhttp.dll",
    "winhttpopenrequest": "winhttp.dll",
    "winhttpconnect": "winhttp.dll",
    "winhttpsendrequest": "winhttp.dll",
    "winhttpreceiveresponse": "winhttp.dll",
    "winhttpreaddata": "winhttp.dll",
    "winhttpclosehandle": "winhttp.dll",
    # KERNEL32.DLL - Toolhelp
    "createtoolhelp32snapshot": "kernel32.dll",
    "process32first": "kernel32.dll",
    "process32next": "kernel32.dll",
    "thread32first": "kernel32.dll",
    "thread32next": "kernel32.dll",
    "module32first": "kernel32.dll",
    "module32next": "kernel32.dll",
    # WININET.DLL - FTP Functions
    "ftpputfile": "wininet.dll",
    "ftpputfilea": "wininet.dll",
    "ftpputfilew": "wininet.dll",
    "ftpgetfile": "wininet.dll",
    "ftpgetfilea": "wininet.dll",
    "ftpgetfilew": "wininet.dll",
    "ftpopenfile": "wininet.dll",
    # NTDLL.DLL - Native API
    "ntunmapviewofsection": "ntdll.dll",
    # SHELL32.DLL - Shell
    "shellexecute": "shell32.dll",
    "shgetfolder": "shell32.dll",
    "shgetspecialfolder": "shell32.dll",
    "shbrowseforfolder": "shell32.dll",
    "dragacceptfiles": "shell32.dll",
    "dragqueryfile": "shell32.dll",
    # CRYPT32.DLL - Certificates
    "certopen": "crypt32.dll",
    "certfind": "crypt32.dll",
    "certclose": "crypt32.dll",
    "certenum": "crypt32.dll",
    # COMCTL32.DLL - Common Controls (EXPANDED)
    "toolbar": "comctl32.dll",
    "createtoolbarex": "comctl32.dll",
    "createtoolbar": "comctl32.dll",
    "listview": "comctl32.dll",
    "treeview": "comctl32.dll",
    "tabcontrol": "comctl32.dll",
    "progressbar": "comctl32.dll",
    "statusbar": "comctl32.dll",
    "initcommoncontrols": "comctl32.dll",
    "initcommoncontrolsex": "comctl32.dll",
    "imagelist_create": "comctl32.dll",
    "imagelist_destroy": "comctl32.dll",
    "imagelist_add": "comctl32.dll",
    "imagelist_remove": "comctl32.dll",
    "imagelist_replace": "comctl32.dll",
    "imagelist_geticon": "comctl32.dll",
    "imagelist_draw": "comctl32.dll",
    "imagelist_drawex": "comctl32.dll",
    "createpropertysheet": "comctl32.dll",
    "propertysheet": "comctl32.dll",
    "createpropertysheetpage": "comctl32.dll",
    "destroypropertysheetpage": "comctl32.dll",
    # MSVCRT.DLL - C Runtime Library
    "malloc": "msvcrt.dll",
    "calloc": "msvcrt.dll",
    "realloc": "msvcrt.dll",
    "free": "msvcrt.dll",
    "memcpy": "msvcrt.dll",
    "memset": "msvcrt.dll",
    "memmove": "msvcrt.dll",
    "memcmp": "msvcrt.dll",
    "strlen": "msvcrt.dll",
    "strcpy": "msvcrt.dll",
    "strcat": "msvcrt.dll",
    "strcmp": "msvcrt.dll",
    "strncmp": "msvcrt.dll",
    "strstr": "msvcrt.dll",
    "strchr": "msvcrt.dll",
    "strrchr": "msvcrt.dll",
    "sprintf": "msvcrt.dll",
    "sscanf": "msvcrt.dll",
    "printf": "msvcrt.dll",
    "fprintf": "msvcrt.dll",
    "fopen": "msvcrt.dll",
    "fclose": "msvcrt.dll",
    "fread": "msvcrt.dll",
    "fwrite": "msvcrt.dll",
    "fseek": "msvcrt.dll",
    "ftell": "msvcrt.dll",
    "exit": "msvcrt.dll",
    "abort": "msvcrt.dll",
    "atexit": "msvcrt.dll",
    "getenv": "msvcrt.dll",
    "system": "msvcrt.dll",
    # WINMM.DLL - Windows Multimedia
    "playsound": "winmm.dll",
    "playsoundw": "winmm.dll",
    "playsoundar": "winmm.dll",
    "timegettime": "winmm.dll",
    "timegetsystemtime": "winmm.dll",
    "timesetvent": "winmm.dll",
    "timekillvent": "winmm.dll",
    "timebeginperiod": "winmm.dll",
    "timeendperiod": "winmm.dll",
    "waveoutopen": "winmm.dll",
    "waveoutclose": "winmm.dll",
    "waveoutwrite": "winmm.dll",
    "waveoutpause": "winmm.dll",
    "waveoutrestart": "winmm.dll",
    "waveoutreset": "winmm.dll",
    "waveoutgetvolume": "winmm.dll",
    "waveoutsetvolume": "winmm.dll",
    "waveinopen": "winmm.dll",
    "waveinclose": "winmm.dll",
    "waveinstart": "winmm.dll",
    "waveinstop": "winmm.dll",
    "waveinreset": "winmm.dll",
    "mciexecute": "winmm.dll",
    "mcisendcommand": "winmm.dll",
    "mcisendstring": "winmm.dll",
    "mcisendstringa": "winmm.dll",
    "mcisendstringw": "winmm.dll",
    # SETUPAPI.DLL - Setup and Device Installation
    "setupdigetdeviceregistrypropertya": "setupapi.dll",
    "setupdigetdeviceregistrypropertyw": "setupapi.dll",
    "setupdienumdeviceinterfaces": "setupapi.dll",
    "setupdigetdeviceinterfacedetaila": "setupapi.dll",
    "setupdigetdeviceinterfacedetailw": "setupapi.dll",
    "setupdicreatedeviceinfolist": "setupapi.dll",
    "setupdidestroydeviceinfolist": "setupapi.dll",
    "setupdienumdeviceinfo": "setupapi.dll",
    "setupdigetclassdevsa": "setupapi.dll",
    "setupdigetclassdevsw": "setupapi.dll",
    "setupdigetclassdevs": "setupapi.dll",
    "setupdiopendevregkey": "setupapi.dll",
    "setupdigetdeviceinstallparamsa": "setupapi.dll",
    "setupdigetdeviceinstallparamsw": "setupapi.dll",
    "setupdisetdeviceinstallparamsa": "setupapi.dll",
    "setupdisetdeviceinstallparamsw": "setupapi.dll",
    # IMAGEHLP.DLL - Image Help Functions
    "mapandload": "imagehlp.dll",
    "unmapandload": "imagehlp.dll",
    "checkapplinst": "imagehlp.dll",
    "gettimestampforloadedlibrary": "imagehlp.dll",
    "imageload": "imagehlp.dll",
    "imageunload": "imagehlp.dll",
    "imagegetdigest": "imagehlp.dll",
    "bindimage": "imagehlp.dll",
    "bindimageex": "imagehlp.dll",
    "rebaseimage": "imagehlp.dll",
    # VERSION.DLL - Version Information
    "getfileversioinfo": "version.dll",
    "getfileversioninfoa": "version.dll",
    "getfileversioninfow": "version.dll",
    "getfileversioninfosize": "version.dll",
    "getfileversioninfosizea": "version.dll",
    "getfileversioninfosizew": "version.dll",
    "verqueryvalue": "version.dll",
    "verqueryvaluea": "version.dll",
    "verqueryvaluew": "version.dll",
    "verlanguagename": "version.dll",
    "verlanguagenamea": "version.dll",
    "verlanguagenamew": "version.dll",
    # NTDLL.DLL - Additional Native API
    "ntcreatefile": "ntdll.dll",
    "ntcreateprocess": "ntdll.dll",
    "ntqueryinformationprocess": "ntdll.dll",
    "ntqueryinformationthread": "ntdll.dll",
    "ntopenprocess": "ntdll.dll",
    "ntopenthread": "ntdll.dll",
    "ntterminateprocess": "ntdll.dll",
    "ntterminatethread": "ntdll.dll",
    "ntclose": "ntdll.dll",
    "ntreadfile": "ntdll.dll",
    "ntwritefile": "ntdll.dll",
    "ntdeviceiocontrolfile": "ntdll.dll",
}


def detect_dll(function_name: str) -> Optional[str]:
    """Return the DLL name based on intelligent keyword matching."""
    func_lower = function_name.lower()

    # Priority matching - longer matches first (more specific)
    matches = [(key, dll) for key, dll in DLL_MAP.items() if key in func_lower]
    if matches:
        # Sort by key length descending (longer = more specific)
        matches.sort(key=lambda x: len(x[0]), reverse=True)
        return matches[0][1]

    # Native API and RTL functions - add ntdll.dll mapping
    if func_lower.startswith(("nt", "zw", "rtl", "ldr")):
        return "ntdll.dll"

    # Additional heuristics for common patterns
    if func_lower.startswith("create"):
        if (
            "processasuser" in func_lower
            or "processwithlogon" in func_lower
            or "processwithtoken" in func_lower
        ):
            return "advapi32.dll"  # Security-related process creation
        elif "process" in func_lower:
            return "kernel32.dll"  # Most process creation functions are in kernel32
        elif "file" in func_lower:
            return "kernel32.dll"
        elif "window" in func_lower:
            return "user32.dll"
        elif "service" in func_lower:
            return "advapi32.dll"
    elif func_lower.startswith("open"):
        if "process" in func_lower:
            return "kernel32.dll"
        elif "thread" in func_lower:
            return "kernel32.dll"
        elif "key" in func_lower:
            return "advapi32.dll"
        elif "service" in func_lower:
            return "advapi32.dll"
    elif func_lower.startswith(("get", "set")):
        if "window" in func_lower:
            return "user32.dll"
        elif "file" in func_lower:
            return "kernel32.dll"
        elif "process" in func_lower:
            return "kernel32.dll" if "psapi" not in func_lower else "psapi.dll"
    elif func_lower.startswith("enum"):
        if "process" in func_lower:
            return "psapi.dll"
        elif "window" in func_lower:
            return "user32.dll"
        elif "service" in func_lower:
            return "advapi32.dll"

    return None
