"""
Known Functions mapping for MANW-NG

Top 100+ functions most used in reverse engineering, malware analysis and CTFs
"""

# Top 100+ funções mais usadas em engenharia reversa, análise de malware e CTFs
KNOWN_FUNCTIONS = {
    # Process/Thread Management (Critical for malware analysis)
    "createprocessw": "processthreadsapi/nf-processthreadsapi-createprocessw",
    "createprocessa": "processthreadsapi/nf-processthreadsapi-createprocessa",
    "createprocess": "processthreadsapi/nf-processthreadsapi-createprocessa",
    "openprocess": "processthreadsapi/nf-processthreadsapi-openprocess",
    "terminateprocess": "processthreadsapi/nf-processthreadsapi-terminateprocess",
    "getcurrentprocess": "processthreadsapi/nf-processthreadsapi-getcurrentprocess",
    "getcurrentprocessid": "processthreadsapi/nf-processthreadsapi-getcurrentprocessid",
    "getcurrentthread": "processthreadsapi/nf-processthreadsapi-getcurrentthread",
    "getcurrentthreadid": "processthreadsapi/nf-processthreadsapi-getcurrentthreadid",
    "createthread": "processthreadsapi/nf-processthreadsapi-createthread",
    "exitprocess": "processthreadsapi/nf-processthreadsapi-exitprocess",
    "exitthread": "processthreadsapi/nf-processthreadsapi-exitthread",
    "suspendthread": "processthreadsapi/nf-processthreadsapi-suspendthread",
    "resumethread": "processthreadsapi/nf-processthreadsapi-resumethread",
    "waitforsingleobject": "synchapi/nf-synchapi-waitforsingleobject",
    "waitformultipleobjects": "synchapi/nf-synchapi-waitformultipleobjects",
    "getexitcodeprocess": "processthreadsapi/nf-processthreadsapi-getexitcodeprocess",
    "setthreadcontext": "processthreadsapi/nf-processthreadsapi-setthreadcontext",
    "getthreadcontext": "processthreadsapi/nf-processthreadsapi-getthreadcontext",
    # Memory Management (Essential for exploitation)
    "virtualalloc": "memoryapi/nf-memoryapi-virtualalloc",
    "virtualfree": "memoryapi/nf-memoryapi-virtualfree",
    "virtualprotect": "memoryapi/nf-memoryapi-virtualprotect",
    "virtualquery": "memoryapi/nf-memoryapi-virtualquery",
    "readprocessmemory": "memoryapi/nf-memoryapi-readprocessmemory",
    "writeprocessmemory": "memoryapi/nf-memoryapi-writeprocessmemory",
    "heapalloc": "heapapi/nf-heapapi-heapalloc",
    "heapfree": "heapapi/nf-heapapi-heapfree",
    "heapcreate": "heapapi/nf-heapapi-heapcreate",
    "heapdestroy": "heapapi/nf-heapapi-heapdestroy",
    "getprocessheap": "heapapi/nf-heapapi-getprocessheap",
    "globalalloc": "winbase/nf-winbase-globalalloc",
    "globalfree": "winbase/nf-winbase-globalfree",
    "localalloc": "winbase/nf-winbase-localalloc",
    "localfree": "winbase/nf-winbase-localfree",
    # File Operations (Common in malware)
    "createfilea": "fileapi/nf-fileapi-createfilea",
    "createfilew": "fileapi/nf-fileapi-createfilew",
    "createfile": "fileapi/nf-fileapi-createfilea",
    "readfile": "fileapi/nf-fileapi-readfile",
    "writefile": "fileapi/nf-fileapi-writefile",
    "closehandle": "handleapi/nf-handleapi-closehandle",
    "deletefilea": "fileapi/nf-fileapi-deletefilea",
    "deletefilew": "fileapi/nf-fileapi-deletefilew",
    "copyfile": "winbase/nf-winbase-copyfilea",
    "copyfilea": "winbase/nf-winbase-copyfilea",
    "copyfilew": "winbase/nf-winbase-copyfilew",
    "movefile": "winbase/nf-winbase-movefilea",
    "movefilea": "winbase/nf-winbase-movefilea",
    "movefilew": "winbase/nf-winbase-movefilew",
    "findfirstfile": "fileapi/nf-fileapi-findfirstfilea",
    "findfirstfilea": "fileapi/nf-fileapi-findfirstfilea",
    "findfirstfilew": "fileapi/nf-fileapi-findfirstfilew",
    "findnextfile": "fileapi/nf-fileapi-findnextfilea",
    "findnextfilea": "fileapi/nf-fileapi-findnextfilea",
    "findnextfilew": "fileapi/nf-fileapi-findnextfilew",
    "findclose": "fileapi/nf-fileapi-findclose",
    "getfileattributes": "fileapi/nf-fileapi-getfileattributesa",
    "setfileattributes": "fileapi/nf-fileapi-setfileattributesa",
    "getfilesize": "fileapi/nf-fileapi-getfilesize",
    "setfilepointer": "fileapi/nf-fileapi-setfilepointer",
    # DLL/Library Loading (Code injection techniques)
    "loadlibrary": "libloaderapi/nf-libloaderapi-loadlibrarya",
    "loadlibrarya": "libloaderapi/nf-libloaderapi-loadlibrarya",
    "loadlibraryw": "libloaderapi/nf-libloaderapi-loadlibraryw",
    "freelibrary": "libloaderapi/nf-libloaderapi-freelibrary",
    "getprocaddress": "libloaderapi/nf-libloaderapi-getprocaddress",
    "getmodulehandle": "libloaderapi/nf-libloaderapi-getmodulehandlea",
    "getmodulehandlea": "libloaderapi/nf-libloaderapi-getmodulehandlea",
    "getmodulehandlew": "libloaderapi/nf-libloaderapi-getmodulehandlew",
    "getmodulefilename": "libloaderapi/nf-libloaderapi-getmodulefilenamea",
    "getmodulefilenamea": "libloaderapi/nf-libloaderapi-getmodulefilenamea",
    "getmodulefilenamew": "libloaderapi/nf-libloaderapi-getmodulefilenamew",
    # Registry (Persistence mechanisms)
    "regopenkeyex": "winreg/nf-winreg-regopenkeyexa",
    "regcreatekey": "winreg/nf-winreg-regcreatekeya",
    "regcreatekeyex": "winreg/nf-winreg-regcreatekeyexa",
    "regqueryvalueex": "winreg/nf-winreg-regqueryvalueexa",
    "regsetvalueex": "winreg/nf-winreg-regsetvalueexa",
    "regdeletekey": "winreg/nf-winreg-regdeletekeya",
    "regdeletevalue": "winreg/nf-winreg-regdeletevaluea",
    "regclosekey": "winreg/nf-winreg-regclosekey",
    "regenumkey": "winreg/nf-winreg-regenumkeya",
    "regenumvalue": "winreg/nf-winreg-regenumvaluea",
    # Network (C&C communication)
    "wsastartup": "winsock/nf-winsock-wsastartup",
    "wsacleanup": "winsock/nf-winsock-wsacleanup",
    "socket": "winsock2/nf-winsock2-socket",
    "connect": "winsock2/nf-winsock2-connect",
    "bind": "winsock2/nf-winsock2-bind",
    "listen": "winsock2/nf-winsock2-listen",
    "accept": "winsock2/nf-winsock2-accept",
    "send": "winsock2/nf-winsock2-send",
    "recv": "winsock2/nf-winsock2-recv",
    "sendto": "winsock2/nf-winsock2-sendto",
    "recvfrom": "winsock2/nf-winsock2-recvfrom",
    "closesocket": "winsock2/nf-winsock2-closesocket",
    "gethostbyname": "winsock/nf-winsock-gethostbyname",
    "inet_addr": "winsock2/nf-winsock2-inet_addr",
    # WinINet (HTTP/Internet functions)
    "internetopena": "wininet/nf-wininet-internetopena",
    "internetopenw": "wininet/nf-wininet-internetopenw",
    "internetopen": "wininet/nf-wininet-internetopena",
    "internetconnecta": "wininet/nf-wininet-internetconnecta",
    "internetconnectw": "wininet/nf-wininet-internetconnectw",
    "internetconnect": "wininet/nf-wininet-internetconnecta",
    "internetreadfile": "wininet/nf-wininet-internetreadfile",
    "internetwritefile": "wininet/nf-wininet-internetwritefile",
    "internetclosehandle": "wininet/nf-wininet-internetclosehandle",
    # Window Management (GUI interaction)
    "findwindow": "winuser/nf-winuser-findwindowa",
    "findwindowa": "winuser/nf-winuser-findwindowa",
    "findwindoww": "winuser/nf-winuser-findwindoww",
    "findwindowex": "winuser/nf-winuser-findwindowexa",
    "enumwindows": "winuser/nf-winuser-enumwindows",
    "getwindowtext": "winuser/nf-winuser-getwindowtexta",
    "getwindowtexta": "winuser/nf-winuser-getwindowtexta",
    "getwindowtextw": "winuser/nf-winuser-getwindowtextw",
    "setwindowtext": "winuser/nf-winuser-setwindowtexta",
    "setwindowtexta": "winuser/nf-winuser-setwindowtexta",
    "setwindowtextw": "winuser/nf-winuser-setwindowtextw",
    "showwindow": "winuser/nf-winuser-showwindow",
    "getforegroundwindow": "winuser/nf-winuser-getforegroundwindow",
    "setforegroundwindow": "winuser/nf-winuser-setforegroundwindow",
    "messagebox": "winuser/nf-winuser-messagebox",
    "messageboxa": "winuser/nf-winuser-messageboxa",
    "messageboxw": "winuser/nf-winuser-messageboxw",
    # System Information
    "getsysteminfo": "sysinfoapi/nf-sysinfoapi-getsysteminfo",
    "getsystemdirectory": "sysinfoapi/nf-sysinfoapi-getsystemdirectorya",
    "getwindowsdirectory": "sysinfoapi/nf-sysinfoapi-getwindowsdirectorya",
    "getcomputername": "winbase/nf-winbase-getcomputernamea",
    "getusername": "winbase/nf-winbase-getusernamea",
    "getusernamea": "winbase/nf-winbase-getusernamea",
    "getusernamew": "winbase/nf-winbase-getusernamew",
    "getversionex": "sysinfoapi/nf-sysinfoapi-getversionexa",
    "gettickcount": "sysinfoapi/nf-sysinfoapi-gettickcount",
    "getsystemtime": "sysinfoapi/nf-sysinfoapi-getsystemtime",
    "getlocaltime": "sysinfoapi/nf-sysinfoapi-getlocaltime",
    "getsystemmetrics": "winuser/nf-winuser-getsystemmetrics",
    # Error Handling
    "getlasterror": "errhandlingapi/nf-errhandlingapi-getlasterror",
    "setlasterror": "errhandlingapi/nf-errhandlingapi-setlasterror",
    "formatmessage": "winbase/nf-winbase-formatmessagea",
    # Cryptography (Common in malware)
    "cryptacquirecontext": "wincrypt/nf-wincrypt-cryptacquirecontexta",
    "cryptcreatehash": "wincrypt/nf-wincrypt-cryptcreatehash",
    "crypthashdata": "wincrypt/nf-wincrypt-crypthashdata",
    "cryptgethashparam": "wincrypt/nf-wincrypt-cryptgethashparam",
    "cryptreleasecontext": "wincrypt/nf-wincrypt-cryptreleasecontext",
    "cryptdestroyhash": "wincrypt/nf-wincrypt-cryptdestroyhash",
    # Services (Malware persistence)
    "openscmanager": "winsvc/nf-winsvc-openscmanagera",
    "createservice": "winsvc/nf-winsvc-createservicea",
    "openservice": "winsvc/nf-winsvc-openservicea",
    "startservice": "winsvc/nf-winsvc-startservicea",
    "controlservice": "winsvc/nf-winsvc-controlservice",
    "deleteservice": "winsvc/nf-winsvc-deleteservice",
    "closeservicehandle": "winsvc/nf-winsvc-closeservicehandle",
    # Shell Operations
    "shgetfolderpath": "shlobj_core/nf-shlobj_core-shgetfolderpatha",
    "shgetfolderpatha": "shlobj_core/nf-shlobj_core-shgetfolderpatha",
    "shgetfolderpathw": "shlobj_core/nf-shlobj_core-shgetfolderpathw",
    "shellexecute": "shellapi/nf-shellapi-shellexecutea",
    "shellexecutea": "shellapi/nf-shellapi-shellexecutea",
    "shellexecutew": "shellapi/nf-shellapi-shellexecutew",
    "shellexecuteex": "shellapi/nf-shellapi-shellexecuteexa",
    # Security & Access Control
    "openprocesstoken": "processthreadsapi/nf-processthreadsapi-openprocesstoken",
    "adjusttokenprivileges": "securitybaseapi/nf-securitybaseapi-adjusttokenprivileges",
    "lookupprivilegevalue": "winbase/nf-winbase-lookupprivilegevaluea",
    "impersonateloggedonuser": "securitybaseapi/nf-securitybaseapi-impersonateloggedonuser",
    "reverttoself": "securitybaseapi/nf-securitybaseapi-reverttoself",
    # Common functions for testing
    "sleep": "synchapi/nf-synchapi-sleep",
    "createtoolhelp32snapshot": "tlhelp32/nf-tlhelp32-createtoolhelp32snapshot",
    "process32first": "tlhelp32/nf-tlhelp32-process32first",
    "process32next": "tlhelp32/nf-tlhelp32-process32next",
    "setwindowshookex": "winuser/nf-winuser-setwindowshookexa",
    "callnexthookex": "winuser/nf-winuser-callnexthookex",
    "unhookwindowshookex": "winuser/nf-winuser-unhookwindowshookex",
    "isdebuggerpresent": "debugapi/nf-debugapi-isdebuggerpresent",
}
