"""
Known Functions mapping for MANW-NG

Top 100+ functions most used in reverse engineering, malware analysis and CTFs
"""

KNOWN_FUNCTIONS = {
    # Process/Thread Management (Critical for malware analysis)
    "createprocessw": "processthreadsapi/nf-processthreadsapi-createprocessw",
    "createprocessa": "processthreadsapi/nf-processthreadsapi-createprocessa",
    "createprocess": "processthreadsapi/nf-processthreadsapi-createprocessa",
    "openprocess": "processthreadsapi/nf-processthreadsapi-openprocess",
    "terminateprocess": "processthreadsapi/nf-processthreadsapi-terminateprocess",
    "getcurrentprocess": "processthreadsapi/nf-processthreadsapi-getcurrentprocess",
    "getcurrentprocessid": "processthreadsapi/nf-processthreadsapi-getcurrentprocessid",
    "getcurrentthread": "processthreadsapi/nf-processthreadsapi-getcurrentthread",
    "getcurrentthreadid": "processthreadsapi/nf-processthreadsapi-getcurrentthreadid",
    "createthread": "processthreadsapi/nf-processthreadsapi-createthread",
    "exitprocess": "processthreadsapi/nf-processthreadsapi-exitprocess",
    "exitthread": "processthreadsapi/nf-processthreadsapi-exitthread",
    "suspendthread": "processthreadsapi/nf-processthreadsapi-suspendthread",
    "resumethread": "processthreadsapi/nf-processthreadsapi-resumethread",
    "waitforsingleobject": "synchapi/nf-synchapi-waitforsingleobject",
    "waitformultipleobjects": "synchapi/nf-synchapi-waitformultipleobjects",
    "getexitcodeprocess": "processthreadsapi/nf-processthreadsapi-getexitcodeprocess",
    "setthreadcontext": "processthreadsapi/nf-processthreadsapi-setthreadcontext",
    "getthreadcontext": "processthreadsapi/nf-processthreadsapi-getthreadcontext",
    # Memory Management (Essential for exploitation)
    "virtualalloc": "memoryapi/nf-memoryapi-virtualalloc",
    "virtualfree": "memoryapi/nf-memoryapi-virtualfree",
    "virtualprotect": "memoryapi/nf-memoryapi-virtualprotect",
    "virtualquery": "memoryapi/nf-memoryapi-virtualquery",
    "readprocessmemory": "memoryapi/nf-memoryapi-readprocessmemory",
    "writeprocessmemory": "memoryapi/nf-memoryapi-writeprocessmemory",
    "heapalloc": "heapapi/nf-heapapi-heapalloc",
    "heapfree": "heapapi/nf-heapapi-heapfree",
    "heapcreate": "heapapi/nf-heapapi-heapcreate",
    "heapdestroy": "heapapi/nf-heapapi-heapdestroy",
    "getprocessheap": "heapapi/nf-heapapi-getprocessheap",
    "globalalloc": "winbase/nf-winbase-globalalloc",
    "globalfree": "winbase/nf-winbase-globalfree",
    "localalloc": "winbase/nf-winbase-localalloc",
    "localfree": "winbase/nf-winbase-localfree",
    # File Operations (Common in malware)
    "createfilea": "fileapi/nf-fileapi-createfilea",
    "createfilew": "fileapi/nf-fileapi-createfilew",
    "createfile": "fileapi/nf-fileapi-createfilea",
    "readfile": "fileapi/nf-fileapi-readfile",
    "writefile": "fileapi/nf-fileapi-writefile",
    "closehandle": "handleapi/nf-handleapi-closehandle",
    "deletefilea": "fileapi/nf-fileapi-deletefilea",
    "deletefilew": "fileapi/nf-fileapi-deletefilew",
    "copyfile": "winbase/nf-winbase-copyfilea",
    "copyfilea": "winbase/nf-winbase-copyfilea",
    "copyfilew": "winbase/nf-winbase-copyfilew",
    "movefile": "winbase/nf-winbase-movefilea",
    "movefilea": "winbase/nf-winbase-movefilea",
    "movefilew": "winbase/nf-winbase-movefilew",
    "findfirstfile": "fileapi/nf-fileapi-findfirstfilea",
    "findfirstfilea": "fileapi/nf-fileapi-findfirstfilea",
    "findfirstfilew": "fileapi/nf-fileapi-findfirstfilew",
    "findnextfile": "fileapi/nf-fileapi-findnextfilea",
    "findnextfilea": "fileapi/nf-fileapi-findnextfilea",
    "findnextfilew": "fileapi/nf-fileapi-findnextfilew",
    "findclose": "fileapi/nf-fileapi-findclose",
    "getfileattributes": "fileapi/nf-fileapi-getfileattributesa",
    "setfileattributes": "fileapi/nf-fileapi-setfileattributesa",
    "getfilesize": "fileapi/nf-fileapi-getfilesize",
    "setfilepointer": "fileapi/nf-fileapi-setfilepointer",
    # DLL/Library Loading (Code injection techniques)
    "loadlibrary": "libloaderapi/nf-libloaderapi-loadlibrarya",
    "loadlibrarya": "libloaderapi/nf-libloaderapi-loadlibrarya",
    "loadlibraryw": "libloaderapi/nf-libloaderapi-loadlibraryw",
    "freelibrary": "libloaderapi/nf-libloaderapi-freelibrary",
    "getprocaddress": "libloaderapi/nf-libloaderapi-getprocaddress",
    "getmodulehandle": "libloaderapi/nf-libloaderapi-getmodulehandlea",
    "getmodulehandlea": "libloaderapi/nf-libloaderapi-getmodulehandlea",
    "getmodulehandlew": "libloaderapi/nf-libloaderapi-getmodulehandlew",
    "getmodulefilename": "libloaderapi/nf-libloaderapi-getmodulefilenamea",
    "getmodulefilenamea": "libloaderapi/nf-libloaderapi-getmodulefilenamea",
    "getmodulefilenamew": "libloaderapi/nf-libloaderapi-getmodulefilenamew",
    # Registry (Persistence mechanisms)
    "regopenkeyex": "winreg/nf-winreg-regopenkeyexa",
    "regcreatekey": "winreg/nf-winreg-regcreatekeya",
    "regcreatekeyex": "winreg/nf-winreg-regcreatekeyexa",
    "regqueryvalueex": "winreg/nf-winreg-regqueryvalueexa",
    "regsetvalueex": "winreg/nf-winreg-regsetvalueexa",
    "regdeletekey": "winreg/nf-winreg-regdeletekeya",
    "regdeletevalue": "winreg/nf-winreg-regdeletevaluea",
    "regclosekey": "winreg/nf-winreg-regclosekey",
    "regenumkey": "winreg/nf-winreg-regenumkeya",
    "regenumvalue": "winreg/nf-winreg-regenumvaluea",
    # Network (C&C communication)
    "wsastartup": "winsock/nf-winsock-wsastartup",
    "wsacleanup": "winsock/nf-winsock-wsacleanup",
    "socket": "winsock2/nf-winsock2-socket",
    "connect": "winsock2/nf-winsock2-connect",
    "bind": "winsock2/nf-winsock2-bind",
    "listen": "winsock2/nf-winsock2-listen",
    "accept": "winsock2/nf-winsock2-accept",
    "send": "winsock2/nf-winsock2-send",
    "recv": "winsock2/nf-winsock2-recv",
    "sendto": "winsock2/nf-winsock2-sendto",
    "recvfrom": "winsock2/nf-winsock2-recvfrom",
    "closesocket": "winsock2/nf-winsock2-closesocket",
    "gethostbyname": "winsock/nf-winsock-gethostbyname",
    "inet_addr": "winsock2/nf-winsock2-inet_addr",
    # WinINet (HTTP/Internet functions)
    "internetopena": "wininet/nf-wininet-internetopena",
    "internetopenw": "wininet/nf-wininet-internetopenw",
    "internetopen": "wininet/nf-wininet-internetopena",
    "internetconnecta": "wininet/nf-wininet-internetconnecta",
    "internetconnectw": "wininet/nf-wininet-internetconnectw",
    "internetconnect": "wininet/nf-wininet-internetconnecta",
    "internetreadfile": "wininet/nf-wininet-internetreadfile",
    "internetwritefile": "wininet/nf-wininet-internetwritefile",
    "internetclosehandle": "wininet/nf-wininet-internetclosehandle",
    # Window Management (GUI interaction)
    "findwindow": "winuser/nf-winuser-findwindowa",
    "findwindowa": "winuser/nf-winuser-findwindowa",
    "findwindoww": "winuser/nf-winuser-findwindoww",
    "findwindowex": "winuser/nf-winuser-findwindowexa",
    "enumwindows": "winuser/nf-winuser-enumwindows",
    "getwindowtext": "winuser/nf-winuser-getwindowtexta",
    "getwindowtexta": "winuser/nf-winuser-getwindowtexta",
    "getwindowtextw": "winuser/nf-winuser-getwindowtextw",
    "setwindowtext": "winuser/nf-winuser-setwindowtexta",
    "setwindowtexta": "winuser/nf-winuser-setwindowtexta",
    "setwindowtextw": "winuser/nf-winuser-setwindowtextw",
    "showwindow": "winuser/nf-winuser-showwindow",
    "getforegroundwindow": "winuser/nf-winuser-getforegroundwindow",
    "setforegroundwindow": "winuser/nf-winuser-setforegroundwindow",
    "messagebox": "winuser/nf-winuser-messagebox",
    "messageboxa": "winuser/nf-winuser-messageboxa",
    "messageboxw": "winuser/nf-winuser-messageboxw",
    # System Information
    "getsysteminfo": "sysinfoapi/nf-sysinfoapi-getsysteminfo",
    "getsystemdirectory": "sysinfoapi/nf-sysinfoapi-getsystemdirectorya",
    "getwindowsdirectory": "sysinfoapi/nf-sysinfoapi-getwindowsdirectorya",
    "getcomputername": "winbase/nf-winbase-getcomputernamea",
    "getusername": "winbase/nf-winbase-getusernamea",
    "getusernamea": "winbase/nf-winbase-getusernamea",
    "getusernamew": "winbase/nf-winbase-getusernamew",
    "getversionex": "sysinfoapi/nf-sysinfoapi-getversionexa",
    "gettickcount": "sysinfoapi/nf-sysinfoapi-gettickcount",
    "getsystemtime": "sysinfoapi/nf-sysinfoapi-getsystemtime",
    "getlocaltime": "sysinfoapi/nf-sysinfoapi-getlocaltime",
    "getsystemmetrics": "winuser/nf-winuser-getsystemmetrics",
    # Error Handling
    "getlasterror": "errhandlingapi/nf-errhandlingapi-getlasterror",
    "setlasterror": "errhandlingapi/nf-errhandlingapi-setlasterror",
    "formatmessage": "winbase/nf-winbase-formatmessagea",
    # Cryptography (Common in malware)
    "cryptacquirecontext": "wincrypt/nf-wincrypt-cryptacquirecontexta",
    "cryptcreatehash": "wincrypt/nf-wincrypt-cryptcreatehash",
    "crypthashdata": "wincrypt/nf-wincrypt-crypthashdata",
    "cryptgethashparam": "wincrypt/nf-wincrypt-cryptgethashparam",
    "cryptreleasecontext": "wincrypt/nf-wincrypt-cryptreleasecontext",
    "cryptdestroyhash": "wincrypt/nf-wincrypt-cryptdestroyhash",
    # Services (Malware persistence)
    "openscmanager": "winsvc/nf-winsvc-openscmanagera",
    "createservice": "winsvc/nf-winsvc-createservicea",
    "openservice": "winsvc/nf-winsvc-openservicea",
    "startservice": "winsvc/nf-winsvc-startservicea",
    "controlservice": "winsvc/nf-winsvc-controlservice",
    "deleteservice": "winsvc/nf-winsvc-deleteservice",
    "closeservicehandle": "winsvc/nf-winsvc-closeservicehandle",
    # Shell Operations
    "shgetfolderpath": "shlobj_core/nf-shlobj_core-shgetfolderpatha",
    "shgetfolderpatha": "shlobj_core/nf-shlobj_core-shgetfolderpatha",
    "shgetfolderpathw": "shlobj_core/nf-shlobj_core-shgetfolderpathw",
    "shellexecute": "shellapi/nf-shellapi-shellexecutea",
    "shellexecutea": "shellapi/nf-shellapi-shellexecutea",
    "shellexecutew": "shellapi/nf-shellapi-shellexecutew",
    "shellexecuteex": "shellapi/nf-shellapi-shellexecuteexa",
    # Security & Access Control
    "openprocesstoken": "processthreadsapi/nf-processthreadsapi-openprocesstoken",
    "adjusttokenprivileges": "securitybaseapi/nf-securitybaseapi-adjusttokenprivileges",
    "lookupprivilegevalue": "winbase/nf-winbase-lookupprivilegevaluea",
    "impersonateloggedonuser": "securitybaseapi/nf-securitybaseapi-impersonateloggedonuser",
    "reverttoself": "securitybaseapi/nf-securitybaseapi-reverttoself",
    # Common functions for testing
    "sleep": "synchapi/nf-synchapi-sleep",
    "createtoolhelp32snapshot": "tlhelp32/nf-tlhelp32-createtoolhelp32snapshot",
    "process32first": "tlhelp32/nf-tlhelp32-process32first",
    "process32next": "tlhelp32/nf-tlhelp32-process32next",
    "setwindowshookex": "winuser/nf-winuser-setwindowshookexa",
    "callnexthookex": "winuser/nf-winuser-callnexthookex",
    "unhookwindowshookex": "winuser/nf-winuser-unhookwindowshookex",
    "isdebuggerpresent": "debugapi/nf-debugapi-isdebuggerpresent",
    # Native API (NTDLL) - Essential for advanced RE/malware analysis
    "ntqueryinformationprocess": "winternl/nf-winternl-ntqueryinformationprocess",
    "ntcreatefile": "winternl/nf-winternl-ntcreatefile",
    # Note: Many NT functions are documented in /windows-hardware/drivers/ddi/ section
    # The discovery engine will automatically find them using multiple URL patterns
    "rtlcreateuserthread": "winternl/nf-winternl-rtlcreateuserthread",
    "rtlcopymemory": "winternl/nf-winternl-rtlcopymemory",
    "rtlmovememory": "winternl/nf-winternl-rtlmovememory",
    "rtlgetprocessheaps": "winternl/nf-winternl-rtlgetprocessheaps",
    "rtlallocateheap": "winternl/nf-winternl-rtlallocateheap",
    "rtlfreeheap": "winternl/nf-winternl-rtlfreeheap",
    "rtlinitializeunicodestring": "winternl/nf-winternl-rtlinitializeunicodestring",
    "rtlunicodetoansii": "winternl/nf-winternl-rtlunicodetoansii",
    "rtlansiitounicode": "winternl/nf-winternl-rtlansiitounicode",
    # RTL Memory Functions (Driver/Kernel level) - Note: these are in windows-hardware section
    # Discovery engine will handle the alternative paths automatically
    # GDI Functions (GUI manipulation)
    "bitblt": "wingdi/nf-wingdi-bitblt",
    "stretchblt": "wingdi/nf-wingdi-stretchblt",
    "createbitmap": "wingdi/nf-wingdi-createbitmap",
    "createcompatiblebitmap": "wingdi/nf-wingdi-createcompatiblebitmap",
    "createcompatibledc": "wingdi/nf-wingdi-createcompatibledc",
    "createdc": "wingdi/nf-wingdi-createdca",
    "deletedc": "wingdi/nf-wingdi-deletedc",
    "deleteobject": "wingdi/nf-wingdi-deleteobject",
    "selectobject": "wingdi/nf-wingdi-selectobject",
    "getdc": "winuser/nf-winuser-getdc",
    "releasedc": "winuser/nf-winuser-releasedc",
    "getdibits": "wingdi/nf-wingdi-getdibits",
    "setdibits": "wingdi/nf-wingdi-setdibits",
    "createdibitmap": "wingdi/nf-wingdi-createdibitmap",
    "createfont": "wingdi/nf-wingdi-createfonta",
    "textout": "wingdi/nf-wingdi-textouta",
    "drawtext": "winuser/nf-winuser-drawtexta",
    "setbkcolor": "wingdi/nf-wingdi-setbkcolor",
    "settextcolor": "wingdi/nf-wingdi-settextcolor",
    "getpixel": "wingdi/nf-wingdi-getpixel",
    "setpixel": "wingdi/nf-wingdi-setpixel",
    # Device Context Functions (Missing functions added)
    "getdevicecaps": "wingdi/nf-wingdi-getdevicecaps",
    # Additional WinINet functions for malware C&C
    "internetopenurla": "wininet/nf-wininet-internetopenurla",
    "internetopenurlw": "wininet/nf-wininet-internetopenurlw",
    "internetopenurl": "wininet/nf-wininet-internetopenurla",
    "httpopenrequest": "wininet/nf-wininet-httpopenrequesta",
    "httpopenrequesta": "wininet/nf-wininet-httpopenrequesta",
    "httpopenrequestw": "wininet/nf-wininet-httpopenrequestw",
    "httpsendrequest": "wininet/nf-wininet-httpsendrequesta",
    "httpsendrequesta": "wininet/nf-wininet-httpsendrequesta",
    "httpsendreqestw": "wininet/nf-wininet-httpsendreqestw",
    "httpaddrequest headers": "wininet/nf-wininet-httpaddreqestheadersa",
    "httpaddreqestheadersa": "wininet/nf-wininet-httpaddreqestheadersa",
    "httpaddreqestheadersw": "wininet/nf-wininet-httpaddreqestheadersw",
    "httpqueryinfo": "wininet/nf-wininet-httpqueryinfoa",
    "httpqueryinfoa": "wininet/nf-wininet-httpqueryinfoa",
    "httpqueryinfow": "wininet/nf-wininet-httpqueryinfow",
    "internetqueryoption": "wininet/nf-wininet-internetqueryoptiona",
    "internetsetoption": "wininet/nf-wininet-internetsetoptiona",
    "internetcrackurl": "wininet/nf-wininet-internetcrackurla",
    "internetcreateurla": "wininet/nf-wininet-internetcreateurla",
    "internetcreateurlw": "wininet/nf-wininet-internetcreateurlw",
    "internetfindnextfile": "wininet/nf-wininet-internetfindnextfilea",
    # Advanced Process/Thread Manipulation
    "createremotethread": "processthreadsapi/nf-processthreadsapi-createremotethread",
    "queueuserapc": "processthreadsapi/nf-processthreadsapi-queueuserapc",
    "alertablewaitsingleobject": "synchapi/nf-synchapi-waitforsingleobjectex",
    "waitforsingleobjectex": "synchapi/nf-synchapi-waitforsingleobjectex",
    "createevent": "synchapi/nf-synchapi-createeventa",
    "createeventa": "synchapi/nf-synchapi-createeventa",
    "createeventw": "synchapi/nf-synchapi-createeventw",
    "setevent": "synchapi/nf-synchapi-setevent",
    "resetevent": "synchapi/nf-synchapi-resetevent",
    "createmutex": "synchapi/nf-synchapi-createmutexa",
    "createmutexa": "synchapi/nf-synchapi-createmutexa",
    "createmutexw": "synchapi/nf-synchapi-createmutexw",
    "releasemutex": "synchapi/nf-synchapi-releasemutex",
    "createsemaphore": "synchapi/nf-synchapi-createsemaphorea",
    "releasesemaphore": "synchapi/nf-synchapi-releasesemaphore",
    "duplicatehandle": "handleapi/nf-handleapi-duplicatehandle",
    "getprocesstimes": "processthreadsapi/nf-processthreadsapi-getprocesstimes",
    "getthreadtimes": "processthreadsapi/nf-processthreadsapi-getthreadtimes",
    "setprocessaffinitymask": "processthreadsapi/nf-processthreadsapi-setprocessaffinitymask",
    "setthreadaffinitymask": "processthreadsapi/nf-processthreadsapi-setthreadaffinitymask",
    "setthreadpriority": "processthreadsapi/nf-processthreadsapi-setthreadpriority",
    "getthreadpriority": "processthreadsapi/nf-processthreadsapi-getthreadpriority",
    "setprocesspriority": "processthreadsapi/nf-processthreadsapi-setprocesspriorityboost",
    # Anti-debugging and evasion
    "checkremotedebuggerpresent": "debugapi/nf-debugapi-checkremotedebuggerpresent",
    "outputdebugstring": "debugapi/nf-debugapi-outputdebugstringa",
    "outputdebugstringa": "debugapi/nf-debugapi-outputdebugstringa",
    "outputdebugstringw": "debugapi/nf-debugapi-outputdebugstringw",
    "beingdebugged": "debugapi/nf-debugapi-isdebuggerpresent",
    "ntqueryinformationtread": "winternl/nf-winternl-ntqueryinformationthread",
    "ntsetinformationthread": "winternl/nf-winternl-ntsetinformationthread",
    "ntsetinformationprocess": "winternl/nf-winternl-ntsetinformationprocess",
    "zwqueryinformationprocess": "winternl/nf-winternl-ntqueryinformationprocess",
    "getthreadid": "processthreadsapi/nf-processthreadsapi-getthreadid",
    "getprocessid": "processthreadsapi/nf-processthreadsapi-getprocessid",
    # Kernel manipulation (driver interaction)
    "createfile": "fileapi/nf-fileapi-createfilea",
    "deviceiocontrol": "ioapiset/nf-ioapiset-deviceiocontrol",
    "getoverlappedresult": "ioapiset/nf-ioapiset-getoverlappedresult",
    # Time manipulation
    "gettickcount64": "sysinfoapi/nf-sysinfoapi-gettickcount64",
    "queryperformancecounter": "profileapi/nf-profileapi-queryperformancecounter",
    "queryperformancefrequency": "profileapi/nf-profileapi-queryperformancefrequency",
    "getsystemtimeasfiletime": "sysinfoapi/nf-sysinfoapi-getsystemtimeasfiletime",
    "filetimetosystemtime": "timezoneapi/nf-timezoneapi-filetimetosystemtime",
    "systemtimetofiletime": "timezoneapi/nf-timezoneapi-systemtimetofiletime",
    # Encryption/Decryption (malware obfuscation)
    "cryptgeneraterandom": "wincrypt/nf-wincrypt-cryptgenrandom",
    "cryptgenrandom": "wincrypt/nf-wincrypt-cryptgenrandom",
    "cryptencrypt": "wincrypt/nf-wincrypt-cryptencrypt",
    "cryptdecrypt": "wincrypt/nf-wincrypt-cryptdecrypt",
    "cryptimportkey": "wincrypt/nf-wincrypt-cryptimportkey",
    "cryptexportkey": "wincrypt/nf-wincrypt-cryptexportkey",
    "cryptgetkeyparam": "wincrypt/nf-wincrypt-cryptgetkeyparam",
    "cryptsetkeyparam": "wincrypt/nf-wincrypt-cryptsetkeyparam",
    "cryptdestroykey": "wincrypt/nf-wincrypt-cryptdestroykey",
    "cryptdecodeobject": "wincrypt/nf-wincrypt-cryptdecodeobject",
    "cryptencodeobject": "wincrypt/nf-wincrypt-cryptencodeobject",
    # String manipulation (common in malware)
    "lstrcpy": "winbase/nf-winbase-lstrcpya",
    "lstrcpya": "winbase/nf-winbase-lstrcpya",
    "lstrcpyw": "winbase/nf-winbase-lstrcpyw",
    "lstrcat": "winbase/nf-winbase-lstrcata",
    "lstrcata": "winbase/nf-winbase-lstrcata",
    "lstrcatw": "winbase/nf-winbase-lstrcatw",
    "lstrlen": "winbase/nf-winbase-lstrlena",
    "lstrlena": "winbase/nf-winbase-lstrlena",
    "lstrlenw": "winbase/nf-winbase-lstrlenw",
    "lstrcmp": "winbase/nf-winbase-lstrcmpa",
    "lstrcmpa": "winbase/nf-winbase-lstrcmpa",
    "lstrcmpw": "winbase/nf-winbase-lstrcmpw",
    "lstrcmpi": "winbase/nf-winbase-lstrcmpia",
    "lstrcmpia": "winbase/nf-winbase-lstrcmpia",
    "lstrcmpiw": "winbase/nf-winbase-lstrcmpiw",
    "multibytetowidechar": "stringapiset/nf-stringapiset-multibytetowidechar",
    "widechartomultibyte": "stringapiset/nf-stringapiset-widechartomultibyte",
    "comparestring": "stringapiset/nf-stringapiset-comparestringa",
    "comparestringa": "stringapiset/nf-stringapiset-comparestringa",
    "comparestringw": "stringapiset/nf-stringapiset-comparestringw",
    # Advanced file operations
    "createfilemapping": "winbase/nf-winbase-createfilemappinga",
    "createfilemappinga": "winbase/nf-winbase-createfilemappinga",
    "createfilemappingw": "winbase/nf-winbase-createfilemappingw",
    "mapviewoffile": "winbase/nf-winbase-mapviewoffile",
    "mapviewoffileex": "winbase/nf-winbase-mapviewoffileex",
    "unmapviewoffile": "winbase/nf-winbase-unmapviewoffile",
    "flushviewoffile": "winbase/nf-winbase-flushviewoffile",
    "lockfile": "fileapi/nf-fileapi-lockfile",
    "lockfileex": "fileapi/nf-fileapi-lockfileex",
    "unlockfile": "fileapi/nf-fileapi-unlockfile",
    "unlockfileex": "fileapi/nf-fileapi-unlockfileex",
    "setendoffile": "fileapi/nf-fileapi-setendoffile",
    "flushfilebuffers": "fileapi/nf-fileapi-flushfilebuffers",
    "getfileattributesex": "fileapi/nf-fileapi-getfileattributesexa",
    "getfilesecurity": "winbase/nf-winbase-getfilesecuritya",
    "setfilesecurity": "winbase/nf-winbase-setfilesecuritya",
    "getfileversion info": "winver/nf-winver-getfileversioninfoa",
    "getfileversioninfoa": "winver/nf-winver-getfileversioninfoa",
    "getfileversioninfow": "winver/nf-winver-getfileversioninfow",
    "verqueryvalue": "winver/nf-winver-verqueryvaluea",
    "verqueryvaluea": "winver/nf-winver-verqueryvaluea",
    "verqueryvaluew": "winver/nf-winver-verqueryvaluew",
    # Environment and system manipulation
    "getenvironmentvariable": "processenv/nf-processenv-getenvironmentvariablea",
    "getenvironmentvariablea": "processenv/nf-processenv-getenvironmentvariablea",
    "getenvironmentvariablew": "processenv/nf-processenv-getenvironmentvariablew",
    "setenvironmentvariable": "processenv/nf-processenv-setenvironmentvariablea",
    "setenvironmentvariablea": "processenv/nf-processenv-setenvironmentvariablea",
    "setenvironmentvariablew": "processenv/nf-processenv-setenvironmentvariablew",
    "expandenvironmentstrings": "processenv/nf-processenv-expandenvironmentstringsa",
    "expandenvironmentstringsa": "processenv/nf-processenv-expandenvironmentstringsa",
    "expandenvironmentstringsw": "processenv/nf-processenv-expandenvironmentstringsw",
    # Command Line Functions (Critical for process analysis)
    "getcommandline": "processenv/nf-processenv-getcommandlinea",
    "getcommandlinea": "processenv/nf-processenv-getcommandlinea",
    "getcommandlinew": "processenv/nf-processenv-getcommandlinew",
    "commandlinetoargv": "shellapi/nf-shellapi-commandlinetoargvw",
    "commandlinetoargvw": "shellapi/nf-shellapi-commandlinetoargvw",
    "getcurrentdirectory": "fileapi/nf-fileapi-getcurrentdirectorya",
    "getcurrentdirectorya": "fileapi/nf-fileapi-getcurrentdirectorya",
    "getcurrentdirectoryw": "fileapi/nf-fileapi-getcurrentdirectoryw",
    "setcurrentdirectory": "fileapi/nf-fileapi-setcurrentdirectorya",
    "setcurrentdirectorya": "fileapi/nf-fileapi-setcurrentdirectorya",
    "setcurrentdirectoryw": "fileapi/nf-fileapi-setcurrentdirectoryw",
    "gettemppathh": "fileapi/nf-fileapi-gettemppatha",
    "gettemppatha": "fileapi/nf-fileapi-gettemppatha",
    "gettemppathhw": "fileapi/nf-fileapi-gettemppath",
    "gettempfilename": "fileapi/nf-fileapi-gettempfilenamea",
    "gettempfilenamea": "fileapi/nf-fileapi-gettempfilenamea",
    "gettempfilenamew": "fileapi/nf-fileapi-gettempfilenamew",
    # Advanced registry manipulation
    "regnotifychangekeyvalue": "winreg/nf-winreg-regnotifychangekeyvalue",
    "regflushkey": "winreg/nf-winreg-regflushkey",
    "regconnectregistry": "winreg/nf-winreg-regconnectregistrya",
    "regconnectregistrya": "winreg/nf-winreg-regconnectregistrya",
    "regconnectregistryw": "winreg/nf-winreg-regconnectregistryw",
    "regloadkey": "winreg/nf-winreg-regloadkeya",
    "regloadkeya": "winreg/nf-winreg-regloadkeya",
    "regloadkeyw": "winreg/nf-winreg-regloadkeyw",
    "regunloadkey": "winreg/nf-winreg-regunloadkeya",
    "regunloadkeya": "winreg/nf-winreg-regunloadkeya",
    "regunloadkeyw": "winreg/nf-winreg-regunloadkeyw",
    "regsavekey": "winreg/nf-winreg-regsavekeya",
    "regsavekeya": "winreg/nf-winreg-regsavekeya",
    "regsavekeyex": "winreg/nf-winreg-regsavekeyexa",
    "regrestorekey": "winreg/nf-winreg-regrestorekeya",
    "regrestorekeya": "winreg/nf-winreg-regrestorekeya",
    "regrestorekeyb": "winreg/nf-winreg-regrestorekeyw",
    # Additional advanced functions commonly used
    "createdirectory": "fileapi/nf-fileapi-createdirectorya",
    "createdirectorya": "fileapi/nf-fileapi-createdirectorya",
    "createdirectoryp": "fileapi/nf-fileapi-createdirectoryw",
    "removedirectory": "fileapi/nf-fileapi-removedirectorya",
    "removedirectorya": "fileapi/nf-fileapi-removedirectorya",
    "removedirectoryy": "fileapi/nf-fileapi-removedirectoryw",
    "getlogicaldrives": "fileapi/nf-fileapi-getlogicaldrives",
    "getlogicaldrivestrings": "fileapi/nf-fileapi-getlogicaldrivestringa",
    "getlogicaldrivestring": "fileapi/nf-fileapi-getlogicaldrivestringa",
    "getlogicaldrivestringw": "fileapi/nf-fileapi-getlogicaldrivestringsw",
    "getdiskfreespace": "fileapi/nf-fileapi-getdiskfreespacea",
    "getdiskfreespacea": "fileapi/nf-fileapi-getdiskfreespacea",
    "getdiskfreespaceex": "fileapi/nf-fileapi-getdiskfreespaceex",
    "getvolumeinformation": "fileapi/nf-fileapi-getvolumeinformationa",
    "getvolumeinformationa": "fileapi/nf-fileapi-getvolumeinformationa",
    "getvolumeinformationw": "fileapi/nf-fileapi-getvolumeinformationw",
    # Console and I/O Functions (Essential for malware analysis)
    "allocconsole": "consoleapi2/nf-consoleapi2-allocconsole",
    "freeconsole": "consoleapi2/nf-consoleapi2-freeconsole",
    "attachconsole": "consoleapi2/nf-consoleapi2-attachconsole",
    "getconsolewindow": "wincon/nf-wincon-getconsolewindow",
    "setconsoletitle": "wincon/nf-wincon-setconsoletitlea",
    "setconsoletitlea": "wincon/nf-wincon-setconsoletitlea",
    "setconsoletitlew": "wincon/nf-wincon-setconsoletitlew",
    "getconsoletitle": "wincon/nf-wincon-getconsoletitlea",
    "getconsoletitlea": "wincon/nf-wincon-getconsoletitlea",
    "getconsoletitlew": "wincon/nf-wincon-getconsoletitlew",
    "writeconsolea": "wincon/nf-wincon-writeconsolea",
    "writeconsolew": "wincon/nf-wincon-writeconsolew",
    "readconsolea": "wincon/nf-wincon-readconsolea",
    "readconsolew": "wincon/nf-wincon-readconsolew",
    # Keyboard and Mouse Input (Keyloggers, input monitoring)
    "getkeystate": "winuser/nf-winuser-getkeystate",
    "getasynckeystate": "winuser/nf-winuser-getasynckeystate",
    "getkeyboardstate": "winuser/nf-winuser-getkeyboardstate",
    "setkeyboardstate": "winuser/nf-winuser-setkeyboardstate",
    "keybd_event": "winuser/nf-winuser-keybd_event",
    "mouse_event": "winuser/nf-winuser-mouse_event",
    "sendinput": "winuser/nf-winuser-sendinput",
    "blockinput": "winuser/nf-winuser-blockinput",
    "getcursorpos": "winuser/nf-winuser-getcursorpos",
    "setcursorpos": "winuser/nf-winuser-setcursorpos",
    "showcursor": "winuser/nf-winuser-showcursor",
    "setcursor": "winuser/nf-winuser-setcursor",
    "getcursor": "winuser/nf-winuser-getcursor",
    "clipcursor": "winuser/nf-winuser-clipcursor",
    # Clipboard Operations (Data exfiltration)
    "openclipboard": "winuser/nf-winuser-openclipboard",
    "closeclipboard": "winuser/nf-winuser-closeclipboard",
    "emptyclipboard": "winuser/nf-winuser-emptyclipboard",
    "getclipboarddata": "winuser/nf-winuser-getclipboarddata",
    "setclipboarddata": "winuser/nf-winuser-setclipboarddata",
    "isclipboardformatavailable": "winuser/nf-winuser-isclipboardformatavailable",
    "enumclipboardformats": "winuser/nf-winuser-enumclipboardformats",
    "registerclipboardformat": "winuser/nf-winuser-registerclipboardformata",
    "registerclipboardformata": "winuser/nf-winuser-registerclipboardformata",
    "registerclipboardformatw": "winuser/nf-winuser-registerclipboardformatw",
    "getclipboardformatname": "winuser/nf-winuser-getclipboardformatnamea",
    "getclipboardformatnamea": "winuser/nf-winuser-getclipboardformatnamea",
    "getclipboardformatnamew": "winuser/nf-winuser-getclipboardformatnamew",
    # Advanced Memory Management (Code injection, process hollowing)
    "virtualallocex": "memoryapi/nf-memoryapi-virtualallocex",
    "virtualfreeex": "memoryapi/nf-memoryapi-virtualfreeex",
    "virtualprotectex": "memoryapi/nf-memoryapi-virtualprotectex",
    "virtualqueryex": "memoryapi/nf-memoryapi-virtualqueryex",
    "flushinstruction cache": "memoryapi/nf-memoryapi-flushinstructioncache",
    "flushinstructioncache": "memoryapi/nf-memoryapi-flushinstructioncache",
    # Process Enumeration (System reconnaissance)
    "enumprocesses": "psapi/nf-psapi-enumprocesses",
    "enumprocessmodules": "psapi/nf-psapi-enumprocessmodules",
    "enumprocessmodulesex": "psapi/nf-psapi-enumprocessmodulesex",
    "getprocessimagefilename": "psapi/nf-psapi-getprocessimagefilenamea",
    "getprocessimagefilenamea": "psapi/nf-psapi-getprocessimagefilenamea",
    "getprocessimagefilenamew": "psapi/nf-psapi-getprocessimagefilenamew",
    "getmodulebasename": "psapi/nf-psapi-getmodulebasenamea",
    "getmodulebasenamea": "psapi/nf-psapi-getmodulebasenamea",
    "getmodulebasenamew": "psapi/nf-psapi-getmodulebasenamew",
    "getmodulefilenames": "psapi/nf-psapi-getmodulefilenameexa",
    "getmodulefilenameex": "psapi/nf-psapi-getmodulefilenameexa",
    "getmodulefilenameexa": "psapi/nf-psapi-getmodulefilenameexa",
    "getmodulefilenameexw": "psapi/nf-psapi-getmodulefilenameexw",
    "getmoduleinformation": "psapi/nf-psapi-getmoduleinformation",
    "getprocessmemoryinfo": "psapi/nf-psapi-getprocessmemoryinfo",
    "getperformanceinfo": "psapi/nf-psapi-getperformanceinfo",
    # Code Page and Encoding (Obfuscation techniques)
    "getacp": "winnls/nf-winnls-getacp",
    "getoemcp": "winnls/nf-winnls-getoemcp",
    "getcpinfo": "winnls/nf-winnls-getcpinfo",
    "getcpinfoexa": "winnls/nf-winnls-getcpinfoexa",
    "getcpinfoexw": "winnls/nf-winnls-getcpinfoexw",
    "isvalidcodepage": "winnls/nf-winnls-isvalidcodepage",
    "setthreadlocale": "winnls/nf-winnls-setthreadlocale",
    "getthreadlocale": "winnls/nf-winnls-getthreadlocale",
    # Windows Management Instrumentation (WMI)
    "coinitialize": "objbase/nf-objbase-coinitialize",
    "coinitializeex": "objbase/nf-objbase-coinitializeex",
    "couninitialize": "objbase/nf-objbase-couninitialize",
    "cocreateinstance": "objbase/nf-objbase-cocreateinstance",
    "clsidfromstring": "objbase/nf-objbase-clsidfromstring",
    "clsidfrompr ogid": "objbase/nf-objbase-clsidfrompr",
    "stringfromclsid": "objbase/nf-objbase-stringfromclsid",
    "stringfromiid": "objbase/nf-objbase-stringfromiid",
    # Event Logging (Anti-forensics)
    "openeventlog": "winbase/nf-winbase-openeventloga",
    "openeventloga": "winbase/nf-winbase-openeventloga",
    "openeventlogw": "winbase/nf-winbase-openeventlogw",
    "cleareventlog": "winbase/nf-winbase-cleareventloga",
    "cleareventloga": "winbase/nf-winbase-cleareventloga",
    "cleareventlogw": "winbase/nf-winbase-cleareventlogw",
    "closeeventlog": "winbase/nf-winbase-closeeventlog",
    "readeventlog": "winbase/nf-winbase-readeventloga",
    "readeventloga": "winbase/nf-winbase-readeventloga",
    "readeventlogw": "winbase/nf-winbase-readeventlogw",
    "reportevent": "winbase/nf-winbase-reporteventa",
    "reporteventa": "winbase/nf-winbase-reporteventa",
    "reporteventw": "winbase/nf-winbase-reporteventw",
    # Directory Operations (File system manipulation)
    "enumdirectorychanges": "winbase/nf-winbase-readdirectorychangesw",
    "readdirectorychanges": "winbase/nf-winbase-readdirectorychangesw",
    "readdirectorychangesw": "winbase/nf-winbase-readdirectorychangesw",
    "getfullpathname": "fileapi/nf-fileapi-getfullpathnamea",
    "getfullpathnamea": "fileapi/nf-fileapi-getfullpathnamea",
    "getfullpathnamew": "fileapi/nf-fileapi-getfullpathnamew",
    "getshortpathname": "fileapi/nf-fileapi-getshortpathnamea",
    "getshortpathnamea": "fileapi/nf-fileapi-getshortpathnamea",
    "getshortpathnamew": "fileapi/nf-fileapi-getshortpathnamew",
    "getlongpathname": "fileapi/nf-fileapi-getlongpathnamea",
    "getlongpathnamea": "fileapi/nf-fileapi-getlongpathnamea",
    "getlongpathnamew": "fileapi/nf-fileapi-getlongpathnamew",
    "pathfindonpath": "shlwapi/nf-shlwapi-pathfindonpatha",
    "pathfindonpatha": "shlwapi/nf-shlwapi-pathfindonpatha",
    "pathfindonpathw": "shlwapi/nf-shlwapi-pathfindonpathw",
    "searchpath": "processenv/nf-processenv-searchpatha",
    "searchpatha": "processenv/nf-processenv-searchpatha",
    "searchpathw": "processenv/nf-processenv-searchpathw",
    # Advanced Synchronization (Rootkit techniques)
    "createiocompletionport": "ioapiset/nf-ioapiset-createiocompletionport",
    "getqueuedcompletionstatus": "ioapiset/nf-ioapiset-getqueuedcompletionstatus",
    "postqueuedcompletionstatus": "ioapiset/nf-ioapiset-postqueuedcompletionstatus",
    "createwaitabletimer": "synchapi/nf-synchapi-createwaitabletimera",
    "createwaitabletimera": "synchapi/nf-synchapi-createwaitabletimera",
    "createwaitabletimerw": "synchapi/nf-synchapi-createwaitabletimerw",
    "setwaitabletimer": "synchapi/nf-synchapi-setwaitabletimer",
    "cancelwaitabletimer": "synchapi/nf-synchapi-cancelwaitabletimer",
    # Image/PE Functions (Malware packing/unpacking)
    "imagehlp_loaddll": "imagehlp/nf-imagehlp-imagehlp_loaddll",
    "imagehlp_unloaddll": "imagehlp/nf-imagehlp-imagehlp_unloaddll",
    "imagentheader": "dbghelp/nf-dbghelp-imagentheader",
    "imagervatova": "imagehlp/nf-imagehlp-imagervatova",
    "imageunload": "imagehlp/nf-imagehlp-imageunload",
    "loadlibrarex": "libloaderapi/nf-libloaderapi-loadlibraryexa",
    "loadlibraryexa": "libloaderapi/nf-libloaderapi-loadlibraryexa",
    "loadlibraryexw": "libloaderapi/nf-libloaderapi-loadlibraryexw",
    "enumresourcetypes": "libloaderapi/nf-libloaderapi-enumresourcetypesa",
    "enumresourcetypesa": "libloaderapi/nf-libloaderapi-enumresourcetypesa",
    "enumresourcetypesw": "libloaderapi/nf-libloaderapi-enumresourcetypesw",
    "enumresourcenames": "libloaderapi/nf-libloaderapi-enumresourcenamesa",
    "enumresourcenamesa": "libloaderapi/nf-libloaderapi-enumresourcenamesa",
    "enumresourcenamesw": "libloaderapi/nf-libloaderapi-enumresourcenamesw",
    "findresource": "libloaderapi/nf-libloaderapi-findresourcea",
    "findresourcea": "libloaderapi/nf-libloaderapi-findresourcea",
    "findresourcew": "libloaderapi/nf-libloaderapi-findresourcew",
    "findresourceex": "libloaderapi/nf-libloaderapi-findresourceexa",
    "findresourceexa": "libloaderapi/nf-libloaderapi-findresourceexa",
    "findresourceexw": "libloaderapi/nf-libloaderapi-findresourceexw",
    "loadresource": "libloaderapi/nf-libloaderapi-loadresource",
    "lockresource": "libloaderapi/nf-libloaderapi-lockresource",
    "sizeofresource": "libloaderapi/nf-libloaderapi-sizeofresource",
    "freeresource": "libloaderapi/nf-libloaderapi-freeresource",
    # System Shutdown/Restart (Destructive malware)
    "exitwindowsex": "winuser/nf-winuser-exitwindowsex",
    "initiatesystemshutdown": "winreg/nf-winreg-initiatesystemshutdowna",
    "initiatesystemshutdowna": "winreg/nf-winreg-initiatesystemshutdowna",
    "initiatesystemshutdownw": "winreg/nf-winreg-initiatesystemshutdownw",
    "initiatesystemshutdownex": "winreg/nf-winreg-initiatesystemshutdownexa",
    "initiatesystemshutdownexa": "winreg/nf-winreg-initiatesystemshutdownexa",
    "initiatesystemshutdownexw": "winreg/nf-winreg-initiatesystemshutdownexw",
    "abortsystemshutdown": "winreg/nf-winreg-abortsystemshutdowna",
    "abortsystemshutdowna": "winreg/nf-winreg-abortsystemshutdowna",
    "abortsystemshutdownw": "winreg/nf-winreg-abortsystemshutdownw",
    # Token Manipulation (Privilege escalation)
    "duplicatetoken": "securitybaseapi/nf-securitybaseapi-duplicatetoken",
    "duplicatetokenex": "securitybaseapi/nf-securitybaseapi-duplicatetokenex",
    "createprocessasuser": "processthreadsapi/nf-processthreadsapi-createprocessasusera",
    "createprocessasusera": "processthreadsapi/nf-processthreadsapi-createprocessasusera",
    "createprocessasuserw": "processthreadsapi/nf-processthreadsapi-createprocessasuserw",
    "createprocesswithtoken": "winbase/nf-winbase-createprocesswithtokenw",
    "createprocesswithtokenw": "winbase/nf-winbase-createprocesswithtokenw",
    "logonuser": "winbase/nf-winbase-logonusera",
    "logonusera": "winbase/nf-winbase-logonusera",
    "logonuserw": "winbase/nf-winbase-logonuserw",
    "gettoken information": "securitybaseapi/nf-securitybaseapi-gettokeninformation",
    "gettokeninformation": "securitybaseapi/nf-securitybaseapi-gettokeninformation",
    "settokeninformation": "securitybaseapi/nf-securitybaseapi-settokeninformation",
}
